### ISSUE TITLE
Hero Siege : Pocket Edition [Hero_Siege]

### ISSUE THREAD

**Issue by DigiD2** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#136]
NOTE: IF YOU'RE SUBMITTING A REPORT FOR A GAMING HAVING ISSUES, PLEASE PERFORM A RUN WITH DEBUG MODE ON AND POST THE RELATED LOG FILE HERE!

# Game summary
- Game name: Hero Siege : Pocket Edition
- Game version: 5.6.10
- https://play.google.com/store/apps/details?id=com.panicartstudios.herosiegepocket&gl=US

# YoYo Loader summary
- Version: v9d6b251

# Issues
- Yoyo loader cannot load libyoyo.so inside of game.apk even though it exists in the correct directory. I have also extracted the assets as well from the obb and still not working. If anyone can get this to work, id highly appreciate it. It is basically diablo 3 in 2d form.

# Screenshots

# Recommended labels
- Not Playable

**Comment by Rinnegatamante** [comment]
Doubt that the file is properly inside the game.apk and/or is of the correct arch or else you won't get that error.

**Comment by DigiD2** [comment]
> Doubt that the file is properly inside the game.apk and/or is of the correct arch or else you won't get that error.

With the other games i have shared here,i have followed the same method with no issues. Change extension of apk to .zip , check for libyoyo.so inside of Lib/armeabi-v7a/ , change back to .apk . For some reason this game and a few others have said " error could not load lib/armeabi-v7a/libyoyo.so from inside game.apk"

Oops im sorry rinne, i meant can not load libyoyo , not "locate" like i said.

**Comment by Rinnegatamante** [comment]
That error is simply impossible that pops up unless said file completely lacks.

**Comment by DigiD2** [comment]
> That error is simply impossible that pops up unless said file completely lacks.

Omg i got it to at least boot! So through some trial and error, i noticed different games have different sized libyoyo.so, most are 4.6mb or 5.26mb or smaller . I just swapped the libyoyo.so to a 5.26mb one and it works BUT it just sits at the studio name and closes the app. Also oddly,if i optimize the apk , libyoyo can not load error pops up again. Siffing through the yyl log seems to say memory allocation failed. Maybe a memory issue.  Not sure as im not to knowledgable on this stuff.

Heres a 
[yyl.log](https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/files/8500528/yyl.log)

**Comment by CatoTheYounger97** [comment]
[Hero_Siege]

**Comment by BonQerss** [comment]
Having the exact same issue, transferred the obb contents into the apk, launched into yoyo loader and it cannot find libyoyo.so 
Here's the full error prompt "Error could not load lib/armeabi-v7a/libyoyo.so from inside game.apk. (Errorcode: 0x80024302)
![image](https://user-images.githubusercontent.com/104710767/180338198-96a8aa8e-ea22-4e14-bd92-c0f62665f05c.png)
and here's an image of the apk with the file actually in there.

**Comment by DigiD2** [comment]
> 

You can do what i did and swap the libyoyo.so with a different one from another game, doing that at least got me a splash screen. I havent tested to see if it works now with all the upgrades and options rinns put in but might be worth a shot. I still think it will fail though as the game is super chunky probably requiring a lot of mem.
