### ISSUE TITLE
Luigi mansion 2d

### ISSUE THREAD

**Issue by MaKun47** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#163]
NOTE: IF YOU'RE SUBMITTING A REPORT FOR A GAMING HAVING ISSUES, PLEASE PERFORM A RUN WITH DEBUG MODE ON AND POST THE RELATED LOG FILE HERE!

# Game summary
- Game name: Luigi mansion 2d?
- Game version: ?

# YoYo Loader summary
- Version: v?

# Issues

# Screenshots
![][(https://gamejolt.com/games/luigis-mansion-2d/504777)

# Recommended labels

- A?
- B?
- C?

**Comment by MaKun47** [comment]
![Uploading 16503260669348966811740163750867.jpg…]()
![Uploading IMG_20220418_205532044.jpg…]()

**Comment by MaKun47** [comment]
![Uploading IMG_20220418_205532044.jpg…]()

**Comment by lxg1202** [comment]
loading crash

**Comment by SetsunaFei** [comment]
Please, write some info for game you tried, and how you run it, etc and share the log file if the game crash or have any issue, 

I look inside the game, it doesnt have data.win, you sure this game made by GMS?

**Comment by MaKun47** [comment]
Tenta a versão APK do game=http://www.mediafire.com/file/ck4magvb8m8xmgk/LUIGI_MANSION_2D.apk/file
