### ISSUE TITLE
Nidhogg

### ISSUE THREAD

**Issue by joulerod** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#175]
Nidhogg

NOTE: IF YOU'RE SUBMITTING A REPORT FOR A GAMING HAVING ISSUES, PLEASE PERFORM A RUN WITH DEBUG MODE ON AND POST THE RELATED LOG FILE HERE!

# Game summary
- Game name: Nidhogg
- Game version: ?
- https://www.mediafire.com/file/r4bfh4l7rz2j2qc/Nidhoggo.apk/file

# YoYo Loader summary
- Version: v0.1(5a61f5)

# Issues
Run with extended Mem Mode
Enable Network Features

Runs 25-30 fps ingame and 40-60 in menu. It seems that online multiplayer works but i didn't find a match

# Screenshots
![IMAG1831](https://user-images.githubusercontent.com/103913658/164152036-ac0ce92d-62d9-412a-8856-2888949936a7.jpg)
![IMAG1833](https://user-images.githubusercontent.com/103913658/164152061-0c816d4d-a717-4152-ace1-d627a3c7ba71.jpg)
![IMAG1832](https://user-images.githubusercontent.com/103913658/164152098-0117f69c-c031-4b2d-abdf-7879d6a80c6b.jpg)

# Recommended labels
- A? Playable
- B?
- C?

**Comment by joulerod** [comment]
Sorry. I didn't realized that there was another post for this title.

**Comment by Rinnegatamante** [comment]
Please, post your findings in the other already existing report.
