### ISSUE TITLE
Undertale [UNDERTALE]

### ISSUE THREAD

**Issue by joulerod** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#178]
NOTE: IF YOU'RE SUBMITTING A REPORT FOR A GAMING HAVING ISSUES, PLEASE PERFORM A RUN WITH DEBUG MODE ON AND POST THE RELATED LOG FILE HERE!

# Game summary
- Game name: Undertale
- Game version: 2.0

# YoYo Loader summary
- Version: Nightly V0.1 (5a61f55)

# Issues
Runs full speed 
Only touch controls

# Screenshots

# Recommended labels

- A Playable
- B?
- C?

**Comment by Rinnegatamante** [comment]
Is it the same executable of this or is it another one? https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/68

**Comment by CatoTheYounger97** [comment]
The same, as there is no official android port.

**Comment by Rinnegatamante** [comment]
Closing since duplicate.
