### ISSUE TITLE
Rite

### ISSUE THREAD

**Issue by vsmgammer** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#247]
NOTE: IF YOU'RE SUBMITTING A REPORT FOR A GAMING HAVING ISSUES, PLEASE PERFORM A RUN WITH DEBUG MODE ON AND POST THE RELATED LOG FILE HERE!

# Game summary
- Game name: rite
- Game version: patch 2 

# YoYo Loader summary
- Version: v0.1 (91759e)

# Issues

No have problems works perfect.
For correct resolution go to opitions in game and fullscreen
Game works 60 FPS

# video
![] https://youtube.com/shorts/rX0ao8Zfpu0?feature=share

# Recommended labels

- A-enable force GLES1
- B-windows fake plataform
- C-image compress

#Game ID: cave

**Comment by SetsunaFei** [comment]
Duplicate #224
